### ISSUE TITLE
psy-maps tools fails on climate.usegalaxy.eu

### ISSUE THREAD

**Issue by annefou** [NordicESMhub/galaxy-tools#27]
- because it tries to create a configuration file in /opt/galaxy/ and this filesystem is readonly.

Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/climate/psy_maps/db8d76da4174/psy_maps/psymap_simple.py", line 31, in <module>
    import psyplot.project as psy  # noqa: I202,E402
  File "/usr/local/tools/_conda/envs/mulled-v1-bc2b1aa7b35a0e77adb619efefa50ceaeb3d54d77eac03581d98a78e6459b045/lib/python3.7/site-packages/psyplot/__init__.py", line 7, in <module>
    from psyplot.config.rcsetup import rcParams
  File "/usr/local/tools/_conda/envs/mulled-v1-bc2b1aa7b35a0e77adb619efefa50ceaeb3d54d77eac03581d98a78e6459b045/lib/python3.7/site-packages/psyplot/config/__init__.py", line 18, in <module>
    config_path = psyplot_fname()
  File "/usr/local/tools/_conda/envs/mulled-v1-bc2b1aa7b35a0e77adb619efefa50ceaeb3d54d77eac03581d98a78e6459b045/lib/python3.7/site-packages/psyplot/config/rcsetup.py", line 921, in psyplot_fname
    configdir = get_configdir()
  File "/usr/local/tools/_conda/envs/mulled-v1-bc2b1aa7b35a0e77adb619efefa50ceaeb3d54d77eac03581d98a78e6459b045/lib/python3.7/site-packages/psyplot/config/rcsetup.py", line 971, in get_configdir
    os.makedirs(p)
  File "/usr/local/tools/_conda/envs/mulled-v1-bc2b1aa7b35a0e77adb619efefa50ceaeb3d54d77eac03581d98a78e6459b045/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/tools/_conda/envs/mulled-v1-bc2b1aa7b35a0e77adb619efefa50ceaeb3d54d77eac03581d98a78e6459b045/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/opt/galaxy/.config'

**Comment by annefou** [comment]
The solution may be to re-define HOME environment variable in xml file e.g.
HOME=`pwd`  &&

**Comment by bgruening** [comment]
see https://github.com/galaxyproject/galaxy/pull/5193

Can you please add a profile (>= 18.01 ) to your tool, than it should work.

**Comment by bgruening** [comment]
I added it manually into the usegalaxy.eu tool, please try it again.

**Comment by annefou** [comment]
seems to be fixed. At least it works on climate galaxy.
